# Generated by Django 3.2 on 2022-11-02 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Travel', 'Travel'), ('School', 'School'), ('Health', 'Health'), ('Personal', 'Personal')], default='Work', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(max_length=2000)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('task_time', models.TimeField(auto_now_add=django.utils.timezone.localtime)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
